# Generated by Django 3.2.12 on 2022-04-11 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Princi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.college')),
            ],
            options={
                'db_table': 'princi',
            },
        ),
    ]
